### PR TITLE
Python3 compatibility for regression test

### PR DESCRIPTION
**Pull request by benzax**
Need to explicitly ask for newline characters to behave consistently

### CODE REVIEW

**Comment by chikinn** [comment]
Hat Player is being fussy:

```
[rk@arch hanabi]$ ./test/regression.py -r
recording test data
[rk@arch hanabi]$ ./test/regression.py
output for newest is unchanged
output for idiot is unchanged
hat has changed
output for cheater is unchanged
output for brainbow is unchanged
```

**Comment by benzax** [comment]
Fascinating.  That I can't repro.  Try printing the entirety of before and
after at line 75.  I should probably perform something like diff to tell
you more usefully how much it changes...

**Comment by chikinn** [comment]
Wow, I can only repro sometimes.  Try this seed: 3181563889912539107

Also: a few min ago I looked up Python diff libs, there are options but apparently nothing that will in one line let me compare two strings, so I got bored.

**Comment by chikinn** [comment]
The difference is only in the last line, apparently.
`Ignoring my discard hint. Cluing instead. {'?': 5, 'b': 3, 'r': 5, 'y': 4, 'w': 5, 'g': 3} 5`
vs.
`Ignoring my discard hint. Cluing instead. {'b': 3, 'y': 4, 'w': 5, 'g': 3, '?': 5, 'r': 5} 5`
The same thing is being printed, just in different orders.

**Comment by benzax** [comment]
Yeah, that is the general cost of writing high level integration tests.  They depend on weird things, and are sometimes flaky.  Python doesn't guarantee that the same dictionary will always print out in the same order.

I could conceivably avoid this issue by sorting the output on a character basis, either per file or per line, and just compare the character contents that way.

For now, I'll leave it as is, but I'll think about what to do with this.

**Pull request merged**
