### PR TITLE
Add regression test

### PR DESCRIPTION
**Pull request by benzax**

### CODE REVIEW

**Comment by chikinn** [comment]
Nice util, might stop me from leaving dangling prints in the future ;)

I tried it out, is this the expected behavior?  I record test data, do nothing else, and then check for changes -- and changes are found.

```
[rk@arch hanabi]$ ./test/regression.py --record
recording test data
[rk@arch hanabi]$ ./test/regression.py
brainbow has changed
idiot has changed
hat has changed
cheater has changed
newest has changed
```

**Comment by benzax** [comment]
Nope.  Take a look at the recorded output, it may not work with Python 3
correctly?

**Comment by chikinn** [comment]
Seems normal:

```
[rk@arch tmp]$ cat brainbow.txt 

ROUND 0:
[HANDS] Brainbow1: 1g 2? 5w 3b
        Brainbow2: 4g 3b 1r 3y
        Brainbow3: 3w 1b 4w 1y
        Brainbow4: 3r 5b 2r 2b
        Brainbow5: 1? 1w 3? 1b
[PLAYS] Brainbow1 [1g 2? 5w 3b] hints 1 to Brainbow2
        Brainbow2 [4g 3b 1r 3y] hints 1 to Brainbow3
        Brainbow3 [3w 1b 4w 1y] hints b to Brainbow5
        Brainbow4 [3r 5b 2r 2b] hints r to Brainbow5
        Brainbow5 [1? 1w 3? 1b] hints 1 to Brainbow1
        Brainbow1 [1g 2? 5w 3b] hints r to Brainbow2
        Brainbow2 [4g 3b 1r 3y] hints 1 to Brainbow3
        Brainbow3 [3w 1b 4w 1y] hints 1 to Brainbow5
        Brainbow4 [3r 5b 2r 2b] discards 3r and draws 2g
        Brainbow5 [1? 1w 3? 1b] plays 1? and draws 4?
        Brainbow1 [1g 2? 5w 3b] hints y to Brainbow3
        Brainbow2 [4g 3b 1r 3y] discards 3y and draws 2?
        Brainbow3 [3w 1b 4w 1y] hints 1 to Brainbow5
        Brainbow4 [5b 2r 2b 2g] discards 5b and draws 4b
        Brainbow5 [1w 3? 1b 4?] plays 1b and draws 2w
        Brainbow1 [1g 2? 5w 3b] hints w to Brainbow2
        Brainbow2 [4g 3b 1r 2?] plays 1r and draws 3g
        Brainbow3 [3w 1b 4w 1y] discards 1b and draws 4r
        Brainbow4 [2r 2b 2g 4b] hints w to Brainbow5
        Brainbow5 [1w 3? 4? 2w] plays 1w and draws 1b
        Brainbow1 [1g 2? 5w 3b] discards 3b and draws 2y
        Brainbow2 [4g 3b 2? 3g] hints 2 to Brainbow4
        Brainbow3 [3w 4w 1y 4r] discards 4w and draws 1r
        Brainbow4 [2r 2b 2g 4b] hints w to Brainbow5
        Brainbow5 [3? 4? 2w 1b] discards 3? and draws 4y
        Brainbow1 [1g 2? 5w 2y] hints 2 to Brainbow2
        Brainbow2 [4g 3b 2? 3g] discards 2? and draws 4?
        Brainbow3 [3w 1y 4r 1r] hints b to Brainbow4
        Brainbow4 [2r 2b 2g 4b] discards 2r and draws 3w
        Brainbow5 [4? 2w 1b 4y] hints 1 to Brainbow1
        Brainbow1 [1g 2? 5w 2y] discards 1g and draws 1?
        Brainbow2 [4g 3b 3g 4?] hints 2 to Brainbow5
        Brainbow3 [3w 1y 4r 1r] discards 4r and draws 5?
        Brainbow4 [2b 2g 4b 3w] hints 2 to Brainbow1
        Brainbow5 [4? 2w 1b 4y] discards 2w and draws 5g
        Brainbow1 [2? 5w 2y 1?] discards 2y and draws 1y
        Brainbow2 [4g 3b 3g 4?] hints 2 to Brainbow1
        Brainbow3 [3w 1y 1r 5?] hints b to Brainbow1
        Brainbow4 [2b 2g 4b 3w] discards 4b and draws 2y
        Brainbow5 [4? 1b 4y 5g] hints 1 to Brainbow1
        Brainbow1 [2? 5w 1? 1y] discards 5w and draws 5r
        Brainbow2 [4g 3b 3g 4?] hints y to Brainbow1
        Brainbow3 [3w 1y 1r 5?] discards 1r and draws 1w
        Brainbow4 [2b 2g 3w 2y] discards 3w and draws 1?
        Brainbow5 [4? 1b 4y 5g] discards 4y and draws 1w
        Brainbow1 [2? 1? 1y 5r] plays 1y and draws 1g
        Brainbow2 [4g 3b 3g 4?] hints y to Brainbow4
        Brainbow3 [3w 1y 5? 1w] hints 2 to Brainbow4
        Brainbow4 [2b 2g 2y 1?] plays 2b and draws 1y
        Brainbow5 [4? 1b 5g 1w] hints g to Brainbow1
        Brainbow1 [2? 1? 5r 1g] plays 2? and draws 4y
        Brainbow2 [4g 3b 3g 4?] discards 4g and draws 2b
        Brainbow3 [3w 1y 5? 1w] hints g to Brainbow1
        Brainbow4 [2g 2y 1? 1y] discards 1y and draws 2g
        Brainbow5 [4? 1b 5g 1w] hints g to Brainbow1
        Brainbow1 [1? 5r 1g 4y] discards 4y and draws 4b
        Brainbow2 [3b 3g 4? 2b] hints 1 to Brainbow1
        Brainbow3 [3w 1y 5? 1w] discards 1w and draws 3?
        Brainbow4 [2g 2y 1? 2g] hints b to Brainbow2
        Brainbow5 [4? 1b 5g 1w] discards 1b and draws 1r
        Brainbow1 [1? 5r 1g 4b] hints b to Brainbow2
        Brainbow2 [3b 3g 4? 2b] discards 2b and draws 3g
        Brainbow3 [3w 1y 5? 3?] hints b to Brainbow2
        Brainbow4 [2g 2y 1? 2g] discards 2y and draws 2r
        Brainbow5 [4? 5g 1w 1r] hints 3 to Brainbow2
        Brainbow1 [1? 5r 1g 4b] discards 1g and draws 4g
        Brainbow2 [3b 3g 4? 3g] plays 3b and draws 2w
        Brainbow3 [3w 1y 5? 3?] hints 2 to Brainbow4
        Brainbow4 [2g 1? 2g 2r] discards 2r and draws 3y
        Brainbow5 [4? 5g 1w 1r] hints 4 to Brainbow1
        Brainbow1 [1? 5r 4b 4g] discards 4g and draws 3r
        Brainbow2 [3g 4? 3g 2w] hints y to Brainbow3
        Brainbow3 [3w 1y 5? 3?] discards 3? and draws 4w
        Brainbow4 [2g 1? 2g 3y] hints 4 to Brainbow1
        Brainbow5 [4? 5g 1w 1r] discards 5g and draws 1g
        Brainbow1 [1? 5r 4b 3r] hints w to Brainbow2
        Brainbow2 [3g 4? 3g 2w] discards 3g and draws 5y
        Brainbow3 [3w 1y 5? 4w] hints g to Brainbow5
        Brainbow4 [2g 1? 2g 3y] discards 1? and draws 4r
        Brainbow5 [4? 1w 1r 1g] hints b to Brainbow1
        Brainbow1 [1? 5r 4b 3r] discards 4b
        Brainbow2 [4? 3g 2w 5y] hints 1 to Brainbow5
        Brainbow3 [3w 1y 5? 4w] discards 3w
        Brainbow4 [2g 2g 3y 4r] hints w to Brainbow2
Score: 8
```

**Comment by benzax** [comment]
Well, as soon as I add '3' to the very first line, I can repro... so it is
definitely something I need that doesn't work in python3.

2016-07-24 7:12 GMT-04:00 chikinn notifications@github.com:

**Comment by benzax** [comment]
newlines...

2016-07-24 7:26 GMT-04:00 Benjamin Zax benzax@gmail.com:

**Comment by chikinn** [comment]
Yeah, I just reached that conclusion too :/

Didn't realize they were handled differently in 2 and 3.

**Pull request merged**
