### PR TITLE
Add better cheating bot (and some minor changes)

### PR DESCRIPTION
**Pull request by fpvandoorn**
I've implemented a cheating bot which actually does well. It wins 90% of the games with 2 players and 97-98% of the times with more players.

This is the first time I've written anything in Python, so I'd love feedback on my coding style or inefficiencies in the code. I'm using Python 2.7 (I'm not wedded to that, that was just the version Python which was already installed on my machine).

Should I move all my helper functions in `cheating_player.py` to `bot_utils.py`?

I'm planning to write a non-cheating bot as well, but this was a good first practice with Python.

### CODE REVIEW

**Comment by chikinn** [comment]
Wonderful!  Welcome and thank you for contributing.  Feel free to add or change whatever makes sense to you!

I want to keep this project in Python 3, so it would be nice if you installed that.  But for now I'm happy to check your contributions and make any small compatibility changes that are needed, it's not hard.

I saw the issues you raised too.  Very good points.

**Comment by chikinn** [comment]
As for whether to move functions to bot_utils, go ahead and do so if you feel like they are general enough that other bots will also be able to take advantage of them.

**Comment by fpvandoorn** [comment]
Ok, I'll try to change to Python 3.
One question: at the top of `hanabi_wrapper` is says `#!/usr/bin/env python`. Doesn't that mean to use Python 2.7 by default?

**Comment by fpvandoorn** [comment]
I'm confused. Is this project currently compatible with Python 3? Because I get errors when running it with Python 3. (Sorry if this is a stupid question)

```
floris@floris-kubuntu:~/projects/hanabi$ python3 hanabi_wrapper.py cheater cheater
Traceback (most recent call last):
  File "hanabi_wrapper.py", line 28, in <module>
    from EncodingPlayer import EncodingPlayer
  File "/home/floris/projects/hanabi/EncodingPlayer.py", line 482
    print r.h[i].cards
          ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by chikinn** [comment]
It's not a stupid question!  And feel free to ask even stupid questions, I'm glad you're here and I'm happy to help you with anything :)

You're right, the project is not fully compatible with Python 3.  Sorry for the confusion.

I haven't yet reviewed some of the recent changes to Encoding Player.  (It's a pretty ambitious player and I'm hoping to look at it more carefully this weekend.)  The guy who wrote it is probably using Python 2.  I believe the rest of the project is compatible.

As for `#!/usr/bin/env python`, I think (?) it doesn't necessarily mean to use Python 2.  It will depend on your system.  I only have one version of Python installed, so `python` for me launches Python 3.

**Comment by fpvandoorn** [comment]
If I understand correctly, on Unix-like systems I think the default is that `python` means `python2`. 
From [this page](https://www.python.org/dev/peps/pep-0394/):

> for the time being, all distributions should ensure that python refers to the same target as python2 . 

But it also says

> however, end users should be aware that python refers to python3 on at least Arch Linux [...], so python should be used in the shebang line only for scripts that are source compatible with both Python 2 and 3

**Comment by chikinn** [comment]
Well, sure enough, I run Arch!  Awkward.

As far as I know the project should be compatible with both Python 2 and 3 (after we fix the `print` calls, etc. you found in `EncodingPlayer`).  So maybe we can put off this issue unless someone finds a Python-3-exclusive feature that they want to add.

**Pull request merged**
