### PR TITLE
Encoding AI changes

### PR DESCRIPTION
**Pull request by robieta**
There are two principle changes. First, I needed several pieces of information to be reported by the wrapper which I added. This should not affect compatibility with other AIs. Second I added my own AI.

### CODE REVIEW

**Comment by ghutchings** [comment]
I'm looking forward to testing your new AI; it looks really interesting. However, you may want to consider merging the state of the current master branch into your own fork, testing to make sure everything still works, and making a new pull request once that's complete. There have been some pretty significant changes and bugfixes introduced since you initially forked the project.

Or, Robert might be doing that for you silently in the background...

Also, it's not clear to me why you needed the extra Windows wrapper. I've been using Windows to develop and test my own changes in vanilla Python 2.7.x and (occasionally) 3.x, and have not had any issues running off the command line. Could you tell me a little more about your setup?

**Comment by chikinn** [comment]
Consider me incapacitated for a while -- just drove from Santa Cruz to San Diego today; now I'm headed to Utah for my grandpa's funeral for the weekend; then my first day at HP is Tues!  So maaaaybe I'll manage to look at this on Weds.

Haven't looked at the conflicts yet but yeah, as Greg said there have been some significant changes to the main branch so some stuff may need to be fixed.  I'm happy to do that, or Taylor, you can take a shot.  I'll check in again on Weds. or so.

I'm excited to see your approach in action!

**Comment by robieta** [comment]
I agree that it makes sense for me to get my my stuff compatible with the
existing framework and then do a pull request. I'll need to learn the new
stuff anyway.

As for the windows wrapper, the reason is that I tend to code in a rather
GUI-esq fashion. Right now I am using the anaconda computing package and
coding in spyder, which as far as I can tell is an iPython implementation.
So rather than doing something like:

> python Script.py arg1 arg2
> I hit f5 and run the script. For the life of me, I can't figure out how to
> run from the spyder console with arguments. So the RunHanabi file was
> written to preserve comparability with the command line way of running the
> wrapper while also allowing my "mash f5" approach. If you know a better way
> to do it, by all means. I'm still relatively new to python so some of the
> nuances escape me.

Regards,

Taylor Robie

**Comment by ghutchings** [comment]
Maybe try this: http://stackoverflow.com/a/26766414

If that doesn't work (it would be the easiest fix!), it may be possible to just modify the default values in lines 35-46 of the latest hanabi_wrapper.py. You can add defaults for players as well. Then, running the script directly in Spyder should work...but you'll want to remember to restore the defaults again before you issue the next pull request. Also, the newest wrapper has a different style for args (ex: `python hanabi_wrapper.py cheater cheater -t purple -n 1000 -v silent`).

And oof to the last part of your message...so you're aware, your replies in this thread are auto-posting to the public GitHub page. They can be edited online, if you so choose. Best of luck getting that resolved!

**Comment by robieta** [comment]
One stealthy edit later... Thanks for letting me know.

**Comment by robieta** [comment]
I made a pull request using the most recent version. You can reject this
pull request.

**Pull request closed without merging**
