### PR TITLE
added requirements.txt and updated readme to have virtualenv and install instructions

### LINKED ISSUE #30: Requirements.txt
Looking into adding web compatibility and a requirements.txt would be good. I can add it - but we should cull the dependencies before adding it.

### PR DESCRIPTION
**Pull request by sean9keenan**
Closes #30

### CODE REVIEW

**Comment by sean9keenan** [comment]
One of the advantages of using a virtualenv is that you can easily run on python 2 vs 3

**Comment by chikinn** [comment]
I installed scipy in a virtualenv but when I run hanabi_wrapper I get an error that numpy is missing.  Should numpy also be in requirements.txt?

**Comment by chikinn** [comment]
However, as Dan requested I'm looking into axing the scipy dependency anyway, so this probably won't be an issue.

**Comment by sean9keenan** [comment]
Yeah, we should add numpy as well - I thought that scipy actually imported numpy but I'd believe that I was wrong :/

After you run the pip installs you want just run `pip freeze` to get the list, and prolly want to change the `==` to `>=`.

I can also make the commit and put it in if you want.

**Pull request merged**
